services:
  app:
    build:
      context: app
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - server

  server:
    restart: "always"
    build:
      context: server
      target: builder
    container_name: parkpal-server
    environment:
      PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    restart: always
    image: postgres:latest
    container_name: parkpal-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - 5432:5432

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
  #   ports:
  #     - "5050:80"
  #   restart: always
networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: database/password.txt
