  const cardContainerStyle = {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, 300px)',
    gap: '1rem',
    maxWidth: "1200px",
    margin: '80px auto 0',
    justifyContent: "center"    
  };

  const cardStyle = {
    minHeight: '400px',
    border: '2px solid #ccc',
    borderRadius: '10px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    backdropFilter: "blur(10px)",
    background: "rgba(255, 255, 255, 0.5)",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.2)",
    border: "1px solid rgba(255, 255, 255, 0.18)",
    borderRadius: "10px",
    fontFamily: 'Bagel Fat One',
    fontWeight: 100,
    fontVariantLigatures: "normal",
    fontSize: "1rem",
    letterSpacing: ".5px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    borderColor: "black",
    transition: "transform -8s, box-shadow 0.3s",
    cursor: "pointer",
    transform: "translateY(0)",
    boxShadow: "0 12px 24px rgba(0, 0, 0, 0.3)",
  };
